src/Controllers/FoodsController.cs
using Microsoft.AspNetCore.Mvc;
using food_detective.Models.RequestModels;
using food_detective.Models;
using food_detective.Security;
using food_detective.Services.FoodCentralApi;

namespace food_detective.Controllers
{
    public class FoodsController : Controller, IFoodController
    {
        private readonly IFoodCentralApiService _apiService;
        public FoodsController(IFoodCentralApiService apiService)
        {
            _apiService = apiService;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetFoods([FromQuery] FoodSearchRequestBody foodSearchRequestBody)
        {
            var foodName = foodSearchRequestBody.query;
            var brand = foodSearchRequestBody.brandOwner;
            foodSearchRequestBody.pageSize = 100;
            foodSearchRequestBody.pageNumber = 1;

            var nullCheckResult = FoodNameNullCheck(foodName);

            if ((nullCheckResult as ViewResult).ViewName == "Error")
            {
                return nullCheckResult;
            }

            foodName = StringExtensions.RemoveHtml(foodName).RemoveUrl();
            brand = string.IsNullOrEmpty(brand) ? brand : StringExtensions.RemoveHtml(brand).RemoveUrl();

            if (string.IsNullOrEmpty(foodName))
            {
                var errorViewModel = new ErrorViewModel
                {
                    Message = "Sorry, the food name provided is invalid. Please review your input and try again."
                };

                return View("Error", errorViewModel);
            }

            var foods = await _apiService.FetchFoods(foodName, brand, foodSearchRequestBody);

            var foodsResponseLengthVerificationResult = FoodsResponseLengthCheck(foods.Foods.Length);

            if ((foodsResponseLengthVerificationResult as ViewResult).ViewName == "Error")
            {
                return foodsResponseLengthVerificationResult;
            }

            var foodArrayViewModel = new FoodArrayViewModel
            {
                Foods = foods.Foods
            };

            return View(foodArrayViewModel);
        }

        private IActionResult FoodsResponseLengthCheck(int foodsResponseLength)
        {
            if (foodsResponseLength == 0)
            {
                var errorViewModel = new ErrorViewModel
                {
                    Message = "Sorry, we couldn't find any foods that match the food name you provided. Please try again."
                };

                return View("Error", errorViewModel);
            }

            return View("SuccessfulFunctionCall");
        }

        private IActionResult FoodNameNullCheck(string foodName)
        {
            if (foodName == null)
            {
                var errorViewModel = new ErrorViewModel
                {
                    Message = "Food name cannot be empty."
                };

                return View("Error", errorViewModel);
            }

            return View("SuccessfulFunctionCall");
        }
    }
}

src/Views/Shared/Index.cshtml
@model food_detective.Models.RequestModels.FoodSearchRequestBody

@using (Html.BeginForm("GetFoods", "Foods", FormMethod.Get))
{   
    <div class="form-group">
        <label for="Food Name">Food Name</label>
        @Html.TextBoxFor(model => model.query, new { @class = "form-control", style = "font-size: 24px"})
    </div>

    <br />

    <div class="form-group">
        <label for="Pass Key">Brand (Optional) </label>
        @Html.TextBoxFor(model => model.brandOwner, new { @class = "form-control" })
    </div>

    <br />

    <button type="submit" class="btn btn-primary">Submit</button>
}

src/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor httpContextAccessor;
@{
    var darkMode = httpContextAccessor.HttpContext.Request.Cookies["DarkMode"] == "true";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Food Detective</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/food_detective.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid" id="themeContainer">
                <a class="navbar-brand" asp-area="" asp-controller="Foods" asp-action="Index">Food Detective</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Foods" asp-action="Index">Home</a>
                </div>
                <div class="dark-mode">
                    <form id="darkModeForm" method="post" asp-controller="Home" asp-action="ToggleDarkMode">
                        <label for="darkModeCheckbox">Dark Mode</label>
                        <label class="dark-mode-toggle">
                            <input type="checkbox" id="darkModeCheckbox" name="darkMode" />
                            <span class="slider"></span>
                        </label>
                    </form>
                </div>
            </div>
        </nav>

        @if (darkMode)
        {
            <link rel="stylesheet" href="~/css/DarkMode.css">
        }
        else
        {
            <link rel="stylesheet" href="~/css/LightMode.css">
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Food Detective
        </div>
    </footer>

    <footer>
        <div class="container">
            <div class="warning">
                <div class="col">
                    <p style="text-align: center;"> The information on this website is not a replacement for professional medical advice, diagnosis or treatment. All content on this website is for general information purposes only and does not replace a consultation with a medical professional.</p>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>